### ISSUE TITLE
Error: Exception in thread "main" java.io.IOException: Stale file handle

### ISSUE THREAD

**Issue by FelipeMSD** [usadellab/Trimmomatic#49]
Dear all,

I'm trying to run Trimmomatic, but for few samples I keep finding this on the error file. Do you have any suggestion of what might be wrong?

`Exception in thread "main" java.io.IOException: Stale file handle
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:355)
	at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:254)
	at java.base/java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:212)
	at java.base/java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:146)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:303)
	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:281)
	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:211)
	at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
	at java.base/java.io.BufferedWriter.write(BufferedWriter.java:233)
	at java.base/java.io.Writer.write(Writer.java:162)
	at org.usadellab.trimmomatic.fastq.FastqSerializer.writeRecord(FastqSerializer.java:63)
	at org.usadellab.trimmomatic.TrimmomaticPE.processSingleThreaded(TrimmomaticPE.java:89)
	at org.usadellab.trimmomatic.TrimmomaticPE.process(TrimmomaticPE.java:316)
	at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:555)
	at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)`

Kind regards,
Felipe

**Comment by Jora1991** [comment]
@FelipeMSD Hello, I also encountered the same error on the cluster. Could you please let me know what caused the issue in your case? Do you have any solutions or suggestions for resolving it? Thank you very much.
