### ISSUE TITLE
ILLUMINACLIP: Unknown Trimmer

### ISSUE THREAD

**Issue by RankAma** [usadellab/Trimmomatic#57]
I've installed Trimmomatic from Bioconda and I'm encountering problems while attempting to trim my .fastq sequences. When I run the following command:

```shell
trimmomatic PE -threads 4 -phred33 SRR25943901_1.fastq SRR25943901_2.fastq \
SRR25943901_1.trimmed.fastq SRR25943901_1un.trimmed.fastq \
SRR25943901_2.trimmed.fq.gz SRR25943901_2un.trimmed.fq.gz \
ILLUMINACLIP:SRR25943901_adapter.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
``` 
I receive the error message:
```shell
Exception in thread "main" java.lang.RuntimeException: Unknown trimmer:  ILLUMINACLIP
        at org.usadellab.trimmomatic.trim.TrimmerFactory.makeTrimmer(TrimmerFactory.java:73)
        at org.usadellab.trimmomatic.Trimmomatic.createTrimmers(Trimmomatic.java:59)
        at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:552)
        at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)

``` 
I've read in some forums that removing spaces in the command might resolve the issue. However, doing so hasn't helped and, in fact, appears to assume that the command line doesn't recognise the first command.

**Comment by muzilalalla** [comment]
Hello! How did you solve the problem ? Please tell me , it is so important for me. Thanks!!!!!
