### ISSUE TITLE
Exception ignored

### ISSUE THREAD

**Issue by arjanvandervelde** [usadellab/Trimmomatic#6]
Hi, 

Trimmomatic (ILLUMINACLIP) exits with return code 0 even though an exception was raised while loading adapter sequences. This makes it hard to catch the error when running from scripts. I'd expect it to error and exit with a non-zero return code. Should the exception be re-raised in this section?

https://github.com/usadellab/Trimmomatic/blob/d89f8b7acfa8279aa1230e40af0093ac55c931d5/src/org/usadellab/trimmomatic/trim/IlluminaClippingTrimmer.java#L69-L76

```
...
...
WINDOW:7:20 TRAILING:3 MINLEN:10
java.io.FileNotFoundException: /usr/local/share/trimmomatic-0.39/adapters/NexteraPE-PE.fr (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.usadellab.trimmomatic.fasta.FastaParser.parse(FastaParser.java:54)
        at org.usadellab.trimmomatic.trim.IlluminaClippingTrimmer.loadSequences(IlluminaClippingTrimmer.java:110)
        at org.usadellab.trimmomatic.trim.IlluminaClippingTrimmer.makeIlluminaClippingTrimmer(IlluminaClippingTrimmer.java:71)
        at org.usadellab.trimmomatic.trim.TrimmerFactory.makeTrimmer(TrimmerFactory.java:32)
        at org.usadellab.trimmomatic.Trimmomatic.createTrimmers(Trimmomatic.java:59)
        at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:552)
        at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)
Quality encoding detected as phred33
Input Read Pairs: 25000 Both Surviving: 25000 (100.00%) Forward Only Surviving: 0 (0.00%) Reverse Only Surviving: 0 (0.00%) Dropped: 0 (0.00%)
TrimmomaticPE: Completed successfully
```

-- Arjan

**Comment by TonyBolger** [comment]
Yes, this is a known issue in previous versions, but should be solved in a soon to be released new version (0.40). You can get a preview from the main branch (as version 0.40rc1), which also includes other improvements e.g. parallel gzip compression for much better performance
