### ISSUE TITLE
Not executable - Reg.

### ISSUE THREAD

**Issue by bioramg** [usadellab/Trimmomatic#64]

**Comment by bioramg** [comment]
Hello Sir, 
I'm trying to trim my genome sequence, but I'm encountering an error. I've installed Trimmomatic both individually and through Anaconda, but I still can't execute it. Can you please suggest where the issue might be? 

Thank you.
java -jar /home/bin/Trimmomatic-0.39/trimmomatic-0.39.jar PE /home/2024/EFA_1.fastq.gz /home/2024/EFA_2.fastq.gz /home/2024/forward_trim.fastq.gz /home/2024/forward_unpaired.fastq.gz /home/2024/reverse_trim.fastq.gz /home/2024/reverse_unpaired.fastq.gz -threads 40 /home/bin/Trimmomatic-0.39/adapters/ILLUMINACLIP:TruSeq3-PE.fa:2:30:10:2:True LEADING:3 TRAILING:3 MINLEN:36

******************************************************************************************************************
TrimmomaticPE: Started with arguments:
 /home/2024/EFA_1.fastq.gz /home/2024/EFA_2.fastq.gz /home/2024/forward_trim.fastq.gz /home/2024/forward_unpaired.fastq.gz /home/2024/reverse_trim.fastq.gz /home/2024/reverse_unpaired.fastq.gz -threads 40 /home/bin/Trimmomatic-0.39/adapters/ILLUMINACLIP:TruSeq3-PE.fa:2:30:10:2:True LEADING:3 TRAILING:3 MINLEN:36
Exception in thread "main" java.lang.RuntimeException: Unknown trimmer: /home/bin/Trimmomatic-0.39/adapters/ILLUMINACLIP
        at org.usadellab.trimmomatic.trim.TrimmerFactory.makeTrimmer(TrimmerFactory.java:73)
        at org.usadellab.trimmomatic.Trimmomatic.createTrimmers(Trimmomatic.java:59)
        at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:552)
        at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)
