### ISSUE TITLE
 False positive：java.io.FileNotFoundException: /tools/Trimmomatic-0.39/adapters.fa (No such file or directory)

### ISSUE THREAD

**Issue by Warelock** [usadellab/Trimmomatic#65]
There is only the adapters folder in the file, but no adapters.fa file：

java.io.FileNotFoundException: /tools/Trimmomatic-0.39/adapters.fa (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at org.usadellab.trimmomatic.fasta.FastaParser.parse(FastaParser.java:54)
        at org.usadellab.trimmomatic.trim.IlluminaClippingTrimmer.loadSequences(IlluminaClippingTrimmer.java:110)
        at org.usadellab.trimmomatic.trim.IlluminaClippingTrimmer.makeIlluminaClippingTrimmer(IlluminaClippingTrimmer.java:71)
        at org.usadellab.trimmomatic.trim.TrimmerFactory.makeTrimmer(TrimmerFactory.java:32)
        at org.usadellab.trimmomatic.Trimmomatic.createTrimmers(Trimmomatic.java:59)
        at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:552)
        at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)

**Comment by sebeier** [comment]
The adapter files `NexteraPE-PE.fa`, `TruSeq2-PE.fa`, `TruSeq2-SE.fa`, `TruSeq3-PE.fa`, `TruSeq3-SE.fa`, `TruSeq3-PE-2.fa` are located in the folder `adapters/`. There is no `adapters.fa` from a default installation.
